application: github-review-bot
runtime: nodejs
vm: true
api_version: 1

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

resources:
  cpu: .5
  memory_gb: 1
  disk_size_gb: 10

manual_scaling:
  instances: 1

handlers:
# - url: /favicon.ico
#   static_files: static/favicon.ico
#   upload: static/favicon.ico
#   secure: always
#
# - url: /hook/.*
#   script: _go_app
#   secure: always
#
# - url: /.*
#   login: admin
#   script: _go_app
#   secure: always
